name: ubuntu 20.04 arm64

on: [push]

jobs:
  build_job:
    # The host should always be linux
    runs-on: ubuntu-22.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu20.04

    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Build artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          run: |
              apt update
              apt install -y  build-essential ninja-build python3-pip python3-dev curl gnupg apt-transport-https


              pip install conan==1.60.0 cmake
              conan user
              conan profile new default --detect --force
              conan profile update settings.compiler.libcxx=libstdc++11 default
              conan config set general.parallel_download=$(nproc)
              conan config set general.cpu_count=$(nproc)
              conan remote add duckstax http://conan.duckstax.com

              chmod 777 recipes-create.sh
              ./recipes-create.sh


              conan user ${{ secrets.CONAN_LOGIN_USERNAME }} -r duckstax  -p ${{ secrets.CONAN_PASSWORD }}
              chmod 777 update-remote.sh
              conan upload "*" --confirm  -r duckstax --all
              ./update-remote.sh
